version: '3'

services:
  mongodb:
    image: mongo:5.0.16
    container_name: healthcare-connect-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata: