version: '3.8'

services:
  bbms-register-service:
    build:
      context: ./bbms-register-service
      dockerfile: Dockerfile
    image: bbms-register-service
    container_name: bbms-register-service
    restart: unless-stopped
    env_file: .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      PORT: ${BBMS_REGISTER_SERVICE_PORT}
    ports:
      - "3001:3001"
    networks:
      - healthcare-connect-network
    depends_on:
      - mongodb

  bbms-authentication-service:
    build:
      context: ./bbms-authentication-service
      dockerfile: Dockerfile
    image: bbms-authentication-service
    container_name: bbms-authentication-service
    restart: unless-stopped
    env_file: .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      PORT: ${BBMS_AUTHENTICATION_SERVICE_PORT}
    ports:
      - "3002:3002"
    networks:
      - healthcare-connect-network
    depends_on:
      - mongodb

  bbms-user-service:
    build:
      context: ./bbms-user-service
      dockerfile: Dockerfile
    image: bbms-user-service
    container_name: bbms-user-service
    restart: unless-stopped
    env_file: .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      PORT: ${BBMS_USER_SERVICE_PORT}
    ports:
      - "3003:3003"
    networks:
      - healthcare-connect-network
    depends_on:
      - mongodb

  bbms-entity-service:
    build:
      context: ./bbms-entity-service
      dockerfile: Dockerfile
    image: bbms-entity-service
    container_name: bbms-entity-service
    restart: unless-stopped
    env_file: .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      PORT: ${BBMS_ENTITY_SERVICE_PORT}
    ports:
      - "3004:3004"
    networks:
      - healthcare-connect-network
    depends_on:
      - mongodb

  bbms-appointment-service:
    build:
      context: ./bbms-appointment-service
      dockerfile: Dockerfile
    image: bbms-appointment-service
    container_name: bbms-appointment-service
    restart: unless-stopped
    env_file: .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      PORT: ${BBMS_APPOINTMENT_SERVICE_PORT}
    ports:
      - "3005:3005"
    networks:
      - healthcare-connect-network
    depends_on:
      - mongodb

  bbms-search-service:
    build:
      context: ./bbms-search-service
      dockerfile: Dockerfile
    image: bbms-search-servicee
    container_name: bbms-search-service
    restart: unless-stopped
    env_file: .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      PORT: ${BBMS_SEARCH_SERVICE_PORT}
    ports:
      - "3006:3006"
    networks:
      - healthcare-connect-network
    depends_on:
      - mongodb

  bbms-events-service:
    build:
      context: ./bbms-events-service
      dockerfile: Dockerfile
    image: bbms-events-service
    container_name: bbms-events-service
    restart: unless-stopped
    env_file: .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      PORT: ${BBMS_EVENTS_SERVICE_PORT}
    ports:
      - "3007:3007"
    networks:
      - healthcare-connect-network
    depends_on:
      - mongodb

  bbms-email-service:
    build:
      context: ./bbms-email-service
      dockerfile: Dockerfile
    image: bbms-email-service
    container_name: bbms-email-service
    restart: unless-stopped
    env_file: .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      PORT: ${BBMS_EMAIL_SERVICE_PORT}
      SENDGRID_KEY: ${SENDGRID_KEY}
    ports:
      - "3008:3008"
    networks:
      - healthcare-connect-network
    depends_on:
      - mongodb

  bbms-inventory-service:
    build:
      context: ./bbms-inventory-service
      dockerfile: Dockerfile
    image: bbms-inventory-service
    container_name: bbms-inventory-service
    restart: unless-stopped
    env_file: .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      PORT: ${BBMS_INVENTORY_SERVICE_PORT}
    ports:
      - "3009:3009"
    networks:
      - healthcare-connect-network
    depends_on:
      - mongodb

  bbms-request-service:
    build:
      context: ./bbms-request-service
      dockerfile: Dockerfile
    image: bbms-request-service
    container_name: bbms-request-service
    restart: unless-stopped
    env_file: .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      PORT: ${BBMS_REQUEST_SERVICE_PORT}
    ports:
      - "3010:3010"
    networks:
      - healthcare-connect-network
    depends_on:
      - mongodb

  bbms-api-gateway:
    build:
      context: ./bbms-api-gateway
      dockerfile: Dockerfile
    image: bbms-api-gateway
    container_name: bbms-api-gateway
    restart: unless-stopped
    env_file: .env
    environment:
      BBMS_REGISTER_SERVICE_NAME: ${BBMS_REGISTER_SERVICE_NAME}
      BBMS_AUTHENTICATION_SERVICE_NAME: ${BBMS_AUTHENTICATION_SERVICE_NAME}
      BBMS_USER_SERVICE_NAME: ${BBMS_USER_SERVICE_NAME}
      BBMS_ENTITY_SERVICE_NAME: ${BBMS_ENTITY_SERVICE_NAME}
      BBMS_APPOINTMENT_SERVICE_NAME: ${BBMS_APPOINTMENT_SERVICE_NAME}
      BBMS_SEARCH_SERVICE_NAME: ${BBMS_SEARCH_SERVICE_NAME}
      BBMS_EVENTS_SERVICE_NAME: ${BBMS_EVENTS_SERVICE_NAME}
      BBMS_EMAIL_SERVICE_NAME: ${BBMS_EMAIL_SERVICE_NAME}
      BBMS_INVENTORY_SERVICE_NAME: ${BBMS_INVENTORY_SERVICE_NAME}
      BBMS_REQUEST_SERVICE_NAME: ${BBMS_REQUEST_SERVICE_NAME}
      BBMS_REGISTER_SERVICE_PORT: ${BBMS_REGISTER_SERVICE_PORT} 
      BBMS_AUTHENTICATION_SERVICE_PORT: ${BBMS_AUTHENTICATION_SERVICE_PORT} 
      BBMS_USER_SERVICE_PORT: ${BBMS_USER_SERVICE_PORT} 
      BBMS_ENTITY_SERVICE_PORT: ${BBMS_ENTITY_SERVICE_PORT} 
      BBMS_APPOINTMENT_SERVICE_PORT: ${BBMS_APPOINTMENT_SERVICE_PORT} 
      BBMS_SEARCH_SERVICE_PORT: ${BBMS_SEARCH_SERVICE_PORT} 
      BBMS_EVENTS_SERVICE_PORT: ${BBMS_EVENTS_SERVICE_PORT} 
      BBMS_EMAIL_SERVICE_PORT: ${BBMS_EMAIL_SERVICE_PORT} 
      BBMS_INVENTORY_SERVICE_PORT: ${BBMS_INVENTORY_SERVICE_PORT} 
      BBMS_REQUEST_SERVICE_PORT: ${BBMS_REQUEST_SERVICE_PORT} 
      PORT: ${BBMS_API_GATEWAY_PORT}
    ports:
      - "3000:3000"
    networks:
      - healthcare-connect-network
  
  mongodb:
    image: mongo:5.0.16
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - healthcare-connect-network

networks:
  healthcare-connect-network:
    driver: bridge

volumes:
  mongodbdata: